name: docker

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - Dockerfile
      - build.sh
  pull_request:
    branches: [ "main" ]
    paths:
      - Dockerfile
      - build.sh

jobs:
  push_to_registry:
    name: Update Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: truexpixels
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: truexpixels/elf-tools
          tags: |
            type=raw,value=latest
      
      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
