name: release

on:
  workflow_dispatch:
    inputs:
      gcc_version:
        required: true
        type: string
      binutils_version:
        required: true
        type: string
      gdb_version:
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: rel
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/create-release@v1
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: rel
          release_name: GCC ${{ inputs.gcc_version }} Binutils ${{ inputs.binutils_version }} GDB ${{ inputs.gdb_version }}
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
  build:
    needs: [release]
    strategy:
      fail-fast: false
      matrix:
        arch: [i386-elf, i686-elf, x86_64-elf, aarch64-elf, riscv64-elf, arm-none-eabi]
        platform: [ubuntu-latest, macos-latest]
    name: ${{ matrix.arch }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |                  
          docker run -v "${{ github.workspace }}:/root" --rm truexpixels/elf-tools -t "${{ matrix.arch }}" -gv ${{ inputs.gcc_version }} -bv ${{ inputs.binutils_version }} -dv ${{ inputs.gdb_version }}
#          cd $GITHUB_WORKSPACE 
#          chmod +x build.sh
#          ./build.sh 
      - name: release linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
#          asset_path: /home/runner/build-${{ matrix.arch }}/${{ matrix.arch }}-tools-linux.zip
          asset_path: ${{ github.workspace }}/build-${{ matrix.arch }}/${{ matrix.arch }}-tools-linux.zip
          asset_name: ${{ matrix.arch }}-tools-linux.zip
          asset_content_type: application/zip
      - name: release win
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/build-${{ matrix.arch }}/${{ matrix.arch }}-tools-windows.zip
          asset_name: ${{ matrix.arch }}-tools-windows.zip
          asset_content_type: application/zip
      - name: release mac
        if: ${{ matrix.platform == 'macos-latest' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/build-${{ matrix.arch }}/${{ matrix.arch }}-tools-macos.zip
          asset_name: ${{ matrix.arch }}-tools-macos.zip
          asset_content_type: application/zip        
