name: release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: rel
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/create-release@v1
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: rel
          release_name: Build
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
  build:
    needs: [release]
    strategy:
      fail-fast: false
      matrix:
        arch: [i386-elf, i686-elf, x86_64-elf, aarch64-elf, riscv64-elf, arm-none-eabi, avr]
        platform: [ubuntu-latest, macos-14]
    name: ${{ matrix.arch }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |                  
          cd $GITHUB_WORKSPACE 
          chmod +x build.sh
          ./build.sh -t "${{ matrix.arch }}"
      - name: release linux
        uses: actions/upload-release-asset@v1
        if: ${{ matrix.platform != 'macos-14' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: /home/runner/${{ matrix.arch }}-tools-linux.zip
          asset_name: ${{ matrix.arch }}-tools-linux.zip
          asset_content_type: application/zip
      #- name: release win
      #  if: ${{ matrix.platform != 'macos-14' }}
      #  uses: actions/upload-release-asset@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    upload_url: ${{ needs.release.outputs.upload_url }}
      #    asset_path: /home/runner/${{ matrix.arch }}-tools-windows.zip
      #    asset_name: ${{ matrix.arch }}-tools-windows.zip
      #    asset_content_type: application/zip
      - name: release mac
        if: ${{ matrix.platform == 'macos-14' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: /Users/runner/${{ matrix.arch }}-tools-macos.zip
          asset_name: ${{ matrix.arch }}-tools-macos.zip
          asset_content_type: application/zip        
