name: release

on:
  workflow_dispatch:
    inputs:
      gcc_version:
        required: true
        type: string
      binutils_version:
        required: true
        type: string
      gdb_version:
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [i386-elf, i686-elf, x86_64-elf, aarch64-elf, riscv64-elf, arm-none-eabi]
    name: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE 
          chmod +x build.sh
          ./build.sh -t "${{ matrix.arch }}" -gv ${{ inputs.gcc_version }} -bv ${{ inputs.binutils_version }} -dv ${{ inputs.gdb_version }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch }}
          path: /home/runner/build-*/*.zip
  # Dont edit, i know this is useless but runners are dying for mem out
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/create-release@v1
        id: release
        with:
          tag_name: ${{ inputs.gcc_version }}
          release_name: GCC ${{ inputs.gcc_version }} Binutils ${{ inputs.binutils_version }} GDB ${{ inputs.gdb_version }}
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
          
  upload_assets:
    runs-on: ubuntu-latest
    needs: [release]
    strategy:
      fail-fast: false
      matrix:
        arch: [i386-elf, i686-elf, x86_64-elf, aarch64-elf, riscv64-elf, arm-none-eabi]
    steps:
    - uses: actions/download-artifact@v3
      id: download_path
      with:
        name: ${{ matrix.arch }}
    - name: release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ${{ steps.download_path.outputs.download-path }}/${{ matrix.arch }}
        asset_name: ${{ matrix.arch }}.zip
        asset_content_type: application/zip
