name: release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64-elf, i386-elf, i686-elf, riscv64-elf, arm-none-eabi, avr]
        platform: [ubuntu-latest, macos-13]
    name: ${{ matrix.arch }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |                  
          cd $GITHUB_WORKSPACE 
          chmod +x build.sh
          ./build.sh -t "${{ matrix.arch }}"
      - name: release linux
        uses: actions/upload-release-asset@v1
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: /home/runner/${{ matrix.arch }}-tools-linux.tar.xz
          asset_name: ${{ matrix.arch }}-tools-linux.zip
          asset_content_type: application/zip
      #- name: release win
      #  if: ${{ matrix.platform != 'macos-14' }}
      #  uses: actions/upload-release-asset@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    upload_url: ${{ github.event.release.upload_url }}
      #    asset_path: /home/runner/${{ matrix.arch }}-tools-windows.tar.xz
      #    asset_name: ${{ matrix.arch }}-tools-windows.zip
      #    asset_content_type: application/zip
      - name: release mac
        if: ${{ matrix.platform == 'macos-13' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: /Users/runner/${{ matrix.arch }}-tools-macos.tar.xz
          asset_name: ${{ matrix.arch }}-tools-macos.zip
          asset_content_type: application/zip        
